1. [NumPy의 배열과 행렬 클래스](#NumPy의-배열과-행렬-클래스)
    - [np.ndarray() 클래스](#np.ndarray()-클래스)
1. [인덱싱](#인덱싱)
1. [정렬](#정렬)
1. [차원 변경](#차원-변경)

# SciPy-NumPy 사용

파이썬은 행렬 자료형을 제공하지 않는다. 배열이라 착갈 할 수 있는 List 형을 제공하지만 나열형 데이터만을 가두는 역할을 한다. 파이썬에서 배열과 행렬 연산을 위해서  수치해석용 파이썬 패키지인 SciPy-Numpy 를 사용한다. 

#### NumPy 특징

numpy와 scipy는 과학, 수학, 공학 등에 사용하는 여러 함수를 포함하고 있는 모듈.
Numpy는 과학 연산을 위한 다차원 배열 처리가 가능한 패키지이다.

 - 다차원 배열 자료 구조인 `ndarray`
 - C로 구현된 배열 연산시 벡터화 연산을 이용 복잡한 선형 대수 연산 가능
 - 배열 인덱싱에 질의Query 기능을 사용할 수 있다.
 
#### 설치와 사용

```terminal
$ pip install --user numpy
```

numpy.[함수,변수,클래스] 형식으로 사용

```python
import numpy
```

일반적으로 `np.[함수, 속성]` 형식으로 사용

```python
import numpy as np
```

접두어를 붙이지 않고 NumPy 패키지 내의 모듈명을 바로 사용할 수 있는데

```python
from numpy import *
```

In [4]:
import numpy as np

### NumPy의 배열과 행렬 클래스

NumPy는 *numpy.ndarray* 와 *numpy.matrix* 클래스를 제공한다.

[numpy.ndarray](https://docs.scipy.org/doc/numpy/reference/generated/numpy.ndarray.html)클래스는 다차원 배열을 사용할 수 있는 파이썬 객체이다.
 - 다차원 가능
 - 연산자의 요소간 곱
 - multiply() 함수의 요소간 곱
 - dot() 함수의 행렬 곱

[matrix]() 는 행렬을 위한 고급 클래스이고 MATLAB 기능을 지원한다.

행렬, 매트릭스 계산을 위해 NumPy에서는 `ndarray()`, `array()`, `matrix()`등으로 *ndarray* 객체를 생성한다.




#### 파이썬 List와 NumPy.ndarray

ndarray 배열 객체와 리스트 객체는 많은 차이가 있다.

우선 리스트 클래스 객체는 각각의 원소가 다른 자료형이 될 수 있다. 그러나 배열 객체 객체는 C언어의 배열처럼 연속적인 메모리 배치를 가지기 때문에 모든 원소가 같은 자료형이어야 한다. 이러한 제약사항이 있는 대신 원소에 대한 접근과 반복문 실행이 빨라진다.



### 배열 생성

NumPy에서 리스트 객체 그리고 `ndarray()`, `arange()`, `array()` 등의 함수로 상황에 맞는 배열을 만들어 사용할 수있다.


### list

In [8]:
[1,2,3]

[1, 2, 3]

In [6]:
np.array([1,2,3])

array([1, 2, 3])


###  `np.ndarray()` 클래스
NumPy에서 `ndarray`는 데이터 형식이다. 비슷하게  `np.array()` 함수는 다른 데이터 구조에서 배열을 만들어 준다.

`ndarray` 클래스는 배열의 형태, 형식, 버퍼 등을 지정 할 수 있는 클래스이다.
 
> numpy.ndarray(shape, dtype, buffer, offst, order )
> - shape : tuple of ints Shape of created array.
> - dtype : data-type, optional Any object that can be interpreted as a numpy data type.
> - buffer : object exposing buffer interface, optional Used to fill the array with data.
> - offset : int, optional Offset of array data in buffer.
> - strides : tuple of ints, optional Strides of data in memory.
> - order : {‘C’, ‘F’}, optional Row-major (C-style) or column-major (Fortran-style) order.


In [ ]:
a = np.ndarray( shape=(2,), dtype=float, order='F') # 2 row

`ndarrray( shape=(,) )` 속성으로 차원을 지정해서 여러 차원을 가진 배열을 만들 수 있다.

그리고 **ndarray** 객체의 내용을 속성으로 참조한다:
- .shape: 배열 차수(크기)
- .dtype: 배열의 데이터 형식.
- .ndim: 차원
- .size: 전체 크기

In [ ]:
a = np.ndarray( shape=(2,2), dtype=float, order='F') # 2x2 행렬
a.shape

### np.arange()

`arange()` 명령은 NumPy 버전의 range 명령이라고 볼 수 있다. 특정한 규칙에 따라 증가하는 수열을 만든다. 즉 arange()는 주어진 구간에 균일한 간격의 숫자 생성, 0부터 시작

In [3]:
np.arange(16.0)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [6]:
x = np.arange(10.0, 20.0)
x

array([10., 11., 12., 13., 14., 15., 16., 17., 18., 19.])

In [ ]:
np.arange(3, 21, 2) # 시작, 끝, 단계

### `np.array()` 함수

array라는 함수에 리스트를 넣으면 배열로 변환해 준다.

In [7]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

### 다차원 배열

```
np.array([[1,2,3],[4,5,6],[7,8,9]])
```

In [9]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
x.shape

(3, 3)

In [11]:
x.ndim

2

## 인덱싱

ndarray의 일부, 특정 요소들을 추출할 수 있다.

1. 특정한 데이터만 추출: 인덱스 값
2. 슬라이싱: 인덱스 범위
3. 팬시 인덱싱: 인덱싱 집합으로 해당 부분을 반환
4. 불린 인덱싱: 특정 조건에 해당하는지 여부로 해당 부분을 반환


### 1) 특정 인덱스만 추출

In [7]:
# 단일 값
x[4]

14.0

In [8]:
# 맨 뒤, 맨 뒤에서 2번째
x[-1], x[-2]

(19.0, 18.0)

In [9]:
# 인덱스의 값 수정
x[2] = 49.0
x[2]

49.0

### NumPy.ndarray 의 Axis

ndarray는 2차원에서 row 방향, column 방향에 대해서 axis 0, axis 1 으로 구성

<img src='https://vrzkj25a871bpq7t1ugcgmn9-wpengine.netdna-ssl.com/wp-content/uploads/2018/11/numpy-arrays-have-axes.png' width='400'>

그래서 2차원 인덱싱 [row=0, col=1] 은 [axis 0=0, axis 1=1] 표현이 정확하다.

3차원 인덱싱은 axis 0, axis 1, axis 2 로 3개의 차원 축을 가진다. 이것은 행, 열, 높이로 이해하면 된다.

#### 참고
 - https://www.sharpsightlabs.com/blog/numpy-axes-explained/

### 2). 슬라이싱

슬라이싱은 **_:_** 기호를 사용해 연속한 데이터의 범위를 잘라내서 추출할 수 있다.

In [15]:
x = np.arange(1,40)

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [18]:
x[:] #all

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39])

In [ ]:
x[1:10] #1~10 사이

In [16]:
x[:4] # 0~3 까지

array([1, 2, 3, 4])

In [17]:
x[4:] # 4~끝 까지

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21,
       22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38,
       39])

### 3) 팬시 인덱싱 (Fancy Indexing)

팬시 인덱싱은 리스트, ndarray 로 인덱스 값을 지정하면 해당 위치의 ndarray 배열을 반환한다.

In [28]:
x = np.arange(1,10)
x[[1,2,3]]

array([2, 3, 4])

In [32]:
print(x[[0,1]]) #

[1 2]


### 4) 불리언 인덱싱 (Boolean Indexing)

불리언 인덱싱은 조건 필터링과 검색을 동시에 할 수 있어서 자주 사용되는 인덱싱 방식이다. 배열의 인데스 표현식에 조건식을 사용할 수 있다.

In [34]:
x = np.arange(1,10)
x > 4           # 4보다 큰 배열의 인덱스 값

array([False, False, False, False,  True,  True,  True,  True,  True])

In [35]:
x[x > 4]

array([5, 6, 7, 8, 9])

### 4) 3차원 데이터

3차원 데이터의 슬라이싱을 다룬다.

In [19]:
x = np.array([[1,2,3],[4,5,6],[7,8,9]])
x[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
x.shape

(3, 3)

다차원 배열에서 인덱스 추출시 `[row, col]` 형식으로 추출, 단 인덱스는 모두 0부터 시작하므로 +1 해서 생각.

In [13]:
print(x[1,2]) #2행 3열
print(x[2,1]) #3행 2열

6
8


In [21]:
print(x[0:2, 0:2]) #1~2행 + 1~2열

[[1 2]
 [4 5]]


In [22]:
print(x[1:3, 0:3]) #2~3행 + 1~3열

[[4 5 6]
 [7 8 9]]


In [23]:
print(x[1:3, :]) #2~3행 + 모든열(1~3)

[[4 5 6]
 [7 8 9]]


In [24]:
print(x[:, :]) #모든 행/열

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
print(x[:2, 1:]) #

[[2 3]
 [5 6]]


In [26]:
print(x[:2, 0]) #

[1 4]


##  정렬

**`np.sort()`**, **`ndarray.sort()`**, **`ndarray.argsort()`** 를 사용해서 배열을 정렬할 수 있다.

### 배열 정렬

NumPy에는 `np.sort()` 와 ndarray의 `ndarray.sort()` 두 메서드가 제공된다.

- np.sort(): 원 배열은 유지하고 **_정렬된 배열_**을 반환
- ndarray.sort(): ndarray 객체의 메서드로 객체의 배열 자체를 정렬한다. 반환은 None을 반환한다.
- 두 메서드 모두 기본으로 오름차순 정렬을 한다.

In [45]:
x = np.array([4, 1, -10, 10, 0, -9])
x, type(x), id(x)

(array([  4,   1, -10,  10,   0,  -9]), numpy.ndarray, 547688181552)

In [46]:
t = np.sort(x)
t, id(t)

(array([-10,  -9,   0,   1,   4,  10]), 547688190160)

In [48]:
t = x.sort()
t, type(t), id(t), x

(None, NoneType, 8417264, array([-10,  -9,   0,   1,   4,  10]))

내림 차순 정렬을 위해서 `[::-1]` 을 사용한다.

In [49]:
np.sort(x)[::-1]

array([ 10,   4,   1,   0,  -9, -10])

#### 축 방향 정렬

배열이 2차원 이상인 경우 axis 축 값을 설정해서 행 방향, 열 방향으로 정렬을 할 수 있다.

In [51]:
x = np.array([[8,12],[7,1]])
np.sort(x, axis=0) # 행 방향 정렬

array([[ 7,  1],
       [ 8, 12]])

In [52]:
np.sort(x, axis=1) # 열 방향 정렬

array([[ 8, 12],
       [ 1,  7]])

### 정렬한 배열의 인덱스

np.argsort() 는 정렬된 배열의 인덱스를 ndarray 형으로 반환한다.

In [54]:
x = np.array([4, 1, -10, 10, 0, -9])
np.sort(x), np.argsort(x)

(array([-10,  -9,   0,   1,   4,  10]), array([2, 5, 4, 1, 0, 3]))

In [55]:
#내림차순정렬
np.sort(x)[::-1], np.argsort(x)[::-1]

(array([ 10,   4,   1,   0,  -9, -10]), array([3, 0, 1, 4, 5, 2]))

## 차원 변경

현재 배열의 차원을 reshape 로 주어진 차원으로 변경해 준다.


#### np.arange().reshape()

ndarray의 reshape 는 배열의 요소를 주어진 행/열의 차원에 따라 변환해 반환한다.

In [56]:
x = np.arange(16.0)
x

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15.])

In [59]:
x.reshape(2,8) #2x8 행렬

array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11., 12., 13., 14., 15.]])

In [60]:
x.reshape(8,2) #8x2 행렬

array([[ 0.,  1.],
       [ 2.,  3.],
       [ 4.,  5.],
       [ 6.,  7.],
       [ 8.,  9.],
       [10., 11.],
       [12., 13.],
       [14., 15.]])

#### reshpae 와 -1

reshape 에 행과 열에 `-1` 인자를 사용하면 원래 ndarray와 호환되는 새 shape로 반환해 준다.

In [62]:
t = x.reshape(1,-1) # 
t.shape, t

((1, 16),
 array([[ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
         13., 14., 15.]]))

In [63]:
t = x.reshape(-1,1) # 1x16 배열 리스트
t.shape, t

((16, 1), array([[ 0.],
        [ 1.],
        [ 2.],
        [ 3.],
        [ 4.],
        [ 5.],
        [ 6.],
        [ 7.],
        [ 8.],
        [ 9.],
        [10.],
        [11.],
        [12.],
        [13.],
        [14.],
        [15.]]))

-1은 (-1,1) 형태로 많이 사용하는데 여러 행을 1개의 열을 가진 배열로 변환한다.

In [64]:
x = np.arange(8)
t = x.reshape((2,2,2)) # 2x2x2 행렬
t.shape

(2, 2, 2)

In [67]:
# 3차원 -> 2차원
z = t.reshape(-1,1)
z.shape, z

((8, 1), array([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7]]))

In [68]:
# 3차원 -> 2차원
z = t.reshape(1,-1)
z.shape, z

((1, 8), array([[0, 1, 2, 3, 4, 5, 6, 7]]))